@HostAddress = http://localhost:5024
@apiVersion = v1.0
@bookId = b64b1a41-8e0b-418c-81c8-28ea5d03c421

GET {{HostAddress}}/api/{{apiVersion}}/Books/
Accept: application/json

###
GET {{HostAddress}}/api/{{apiVersion}}/Books/{{bookId}}
Accept: application/json

###
POST {{HostAddress}}/api/{{apiVersion}}/Books/
Content-Type: application/json

{
  "Title": "The Great Gatsby",
  "Author": "F. Scott Fitzgerald",
  "publishedYear": 1925
}

###
PUT {{HostAddress}}/api/{{apiVersion}}/Books/{{bookId}}
Content-Type: application/json

{
    "Title": "The Great Gatsby - Updated Edition",
    "Author": "F. Scott Fitzgerald",
    "publishedYear": 1925
}

###
DELETE {{HostAddress}}/api/{{apiVersion}}/Books/{{bookId}}
Accept: application/json